main: de.craftlancer.imagemaps.ImageMaps
author: SydMontague
version: ${project.version}
name: ImageMaps-1.8
commands:
    imagemap:
        usage: |
          /imagemap <file> <fastsend> - then rightlick on a block, fastsend is either true or false
          /imagemap <file> reload - reloads the imagefile
        permission: imagemaps.use
permissions:
    imagemaps.use:
        default: op
    imagemaps.download:
        default: op